---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackedit
  labels:
    app: stackedit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackedit
  template:
    metadata:
      labels:
        app: stackedit
    spec:
      containers:
        - name: stackedit
          image: benweet/stackedit:latest
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: stackedit
  labels:
    name: stackedit
spec:
  selector:
    app: stackedit
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stackedit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: default
spec:
  rules:
    - host: stackedit.myhost.io
      http:
        paths:
          - path: /
            backend:
              serviceName: stackedit
              servicePort: 8080
